# Brewfile
cask_args appdir: "/Applications"

## Fundamentals
brew "git"
brew "python3"

## SHELL
brew "zsh"

# System
## Utilities
brew "tree"
brew "tmux"
brew "tldr"
brew "bat"
brew "autojump"

## Search
brew "ripgrep"
brew "fd"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

# Dev
brew "neovim"
brew "git-delta"

# Applications
## Media
cask "calibre"

## Productivity
cask "brave-browser"
cask "google-backup-and-sync"
cask "typora"
cask "spark"
cask "nextcloud"

## Developement
cask "visual-studio-code"
cask "iterm2"
cask "drawio"
cask "meld"


### Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-ubuntu-mono-nerd-font"
cask "font-ibm-plex-mono"
